### ISSUE TITLE
In the end of compiling, I always had this problem

### ISSUE THREAD

**Issue by gitdebug** [viptokens/vip#1]
I'm running Ubuntu 14.04 64bit, a dedicated server with 2GB ram and 600GB disk

/home/user/source/vip/src/leveldb/libleveldb.a(env_posix.o): In function `leveldb::(anonymous namespace)::PosixEnv::LockFile(std::string const&, leveldb::FileLock**)':
env_posix.cc:(.text+0x33a5): undefined reference to `operator new(unsigned int)'
env_posix.cc:(.text+0x34e6): undefined reference to `operator new(unsigned int)'
/home/user/source/vip/src/leveldb/libleveldb.a(env_posix.o): In function `leveldb::PosixLogger::Logv(char const*, char*)':
env_posix.cc:(.text._ZN7leveldb11PosixLogger4LogvEPKcPc[_ZN7leveldb11PosixLogger4LogvEPKcPc]+0x156): undefined reference to `operator new[](unsigned int)'
collect2: error: ld returned 1 exit status

**Comment by LeChuckDE** [comment]
Wrong libleveldb Version ...
please Post the output of : 

sudo dpkg --list |grep libleveldb-dev

**Comment by gitdebug** [comment]
I've solved it by trying this :

```
cd src/leveldb 
chmod 755 build_detect_platform
make libleveldb.a libmemenv.a
```

Back to src, and run `make -f makefile.unix`. I tried to compile it at another server, and also failed, so the quieckest way were copying a libleveldb file from Stepscoin
